### ISSUE TITLE
role network not writing correct interfaces files on debian 9

### ISSUE THREAD

**Issue by oxivanisher** [adfinis-sygroup/ansible-roles#64]
On (at least) Debian 9, this role writes a not working DNS configuration, since the `/etc/resolv.conf` is managed by systemd and changes by the role are overwritten. The fix is, that the DNS settings need to be written into the `/etc/networking/interfaces.d/` files instead of `/etc/resolv.conf`.

Things to take into account:
* The role must be idempotent. So it might have to take the OS version into consideration.
* The same fix will probably affect RedHat too, so it has to be fixed there also.

Helpful Link and hint: https://wiki.ubuntuusers.de/interfaces/
```
    [..]
    dns-nameservers 10.2.4.1 95.128.34.42
    dns-search adfinis-sygroup.ch
```

**Comment by tongpu** [comment]
This repository is deprecated, I've moved your issue to https://github.com/adfinis-sygroup/ansible-role-network/issues/10
